"""Add Spanish translations

Revision ID: 8c4ff312bfc7
Revises: da32293e9c61
Create Date: 2026-03-13 23:24:00.834605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4ff312bfc7'
down_revision = 'da32293e9c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('excerpt_es', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('content_es', sa.Text(), nullable=True))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsibilities_es', sa.Text(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('git_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('git_icon', sa.String(length=50), nullable=True))

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_es', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('name_es')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('git_icon')
        batch_op.drop_column('git_url')
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('responsibilities_es')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('content_es')
        batch_op.drop_column('excerpt_es')
        batch_op.drop_column('title_es')

    # ### end Alembic commands ###
