"""Add User model

Revision ID: 931c2757f108
Revises: f2142053d716
Create Date: 2026-02-19 23:33:59.576428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931c2757f108'
down_revision = 'f2142053d716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
