"""Replace _es columns with translations JSON

Revision ID: e14458c8dfcb
Revises: 8c4ff312bfc7
Create Date: 2026-03-13 23:40:07.268681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14458c8dfcb'
down_revision = '8c4ff312bfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))
        batch_op.drop_column('excerpt_es')
        batch_op.drop_column('content_es')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))
        batch_op.drop_column('title_es')
        batch_op.drop_column('responsibilities_es')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))
        batch_op.drop_column('name_es')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_es', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('translations')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.TEXT(), nullable=True))
        batch_op.drop_column('translations')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibilities_es', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('translations')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('content_es', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('excerpt_es', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('translations')

    # ### end Alembic commands ###
